export const APP_URLS = {
  home: '/',
  shop: '/shop',
  about: '/about',
  shipping: '/shipping',
  returns: '/returns',
  contact: '/contact',
  privacy: '/privacy',
  terms: '/terms',
  cart: '/cart',
  cartSuccess: '/cart/success',
  cartFail: '/cart/fail',
  wishlist: '/wishlist',
  account: '/account',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  authCallback: '/auth/callback',
} as const
